# Default values for ssp-analytics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

customui:
  cmsUrl: "http://cms.customui.com:8080/otp.html"
  auth:
    name: customui-auth
    port: 80
  cms:
    name: customui-cms
    port: 8080


