apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.customui.cms.name }}
  name: {{ .Values.customui.cms.name }}
spec:
  selector:
    app: {{ .Values.customui.cms.name }}
  ports:
  - protocol: TCP
    name: web
    port: {{ .Values.customui.cms.port }}
    targetPort: {{ .Values.customui.cms.port }}
  type: LoadBalancer
